apiVersion: v1
kind: Namespace
metadata:
  name: blog
  labels:
    app: blog

# dns <service-name>.<namespace-name>.svc.cluster.local
---
#apiVersion: v1
#kind: LimitRange
#metadata:
#  namespace: blog
#  name: blogs-limit-range
#  labels:
#    app: blogs
#spec:
#  limits:
#    - type: Container
#      default:
#        memory: 3072Mi
#        cpu: "1"
#      defaultRequest:
#        memory: 1024Mi
#        cpu: "0.5"
#      max:
#        memory: 3072Mi
#      min:
#        memory: 1024Mi
#---
#apiVersion: v1
#kind: ResourceQuota
#metadata:
#  namespace: blog
#  name: blogs-resource-quota
#  labels:
#    app: blog
#spec:
#  hard:
#    pods: "3"
#    services: "3"
#    replicationcontrollers: "3"
#    resourcequotas: "3"
#    secrets: "3"
#    configmaps: "3"
#    persistentvolumeclaims: "1"
#    services.loadbalancers: "2"
#    services.nodeports: "0"